name: primer-ejemplo
on: [push]
jobs:
  linter:
   name:linter-execution
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2
       uses: github/super-linter@v3
       env:
        DEFAULT_BRANCH: nodejs_example
	GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
        LINTER_RULES_PATH: /
	JAVASCRIPT_ES_CONFIG_FILE:.eslintrc.jsn
	VALIDATE_JAVASCRIPT_ES: true
