name: activity
on:
  push:
    branches:
      - react_app_deploy
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -D && npm run
      - uses: actions/upload-artifact@v3
        with:
          name: react
          path: my-react-app/index.js
  deploy-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: react
          path: my-react-app/index.js
      - uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'rafaferridomain.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }} 