name: activityRafa
on:
  push:
    branches:
    - nodejs_environment_job
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_linter_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    runs-on: ubuntu-latest
    needs: linter-execution
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest tests
        run: npm install jest && npm test
  environment_test_execution:
    runs-on: ubuntu-latest
    needs: test-execution
    steps:
      - name: environment
        id: hello
        uses: adeloyedeji/github-actions-hello@v1.0 
        with:
            who-to-greet: '2DAW Rafa_'