name: send_telegram_workflow
on:
  push:
    branches:
      - "send_telegram_action"
jobs:
  envio_mensaje:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./src/
        with:
          token: ${{secrets.TOKEN}}
          user: ${{secrets.USER_ID}}